### ISSUE TITLE
UI BUGS: Widget

### ISSUE THREAD

**Issue by tammy-culture** [culturecreates/footlight-app#1036]
WIDGET UI BUGS to fix for DICI.ca (Culture Mauricie)
```[tasklist]
### Tasks
- [x] Widget label: Largeur.  Should be translated to Hauteur
- [x] Calendar widget text should be provided by: DICI.ca and not Culture Mauricie. In French the text is the following: fournie par DICI.ca (and not Culture Mauricie)
- [x] Calendar in widget does not display in the right language. DICI.ca is a french calendar and their widget calendar displays in English. This should be fixed. Specifically the dates like March should be mars in French.
```
Examples are below.

**Comment by tammy-culture** [comment]
![Image](https://github.com/culturecreates/footlight-app/assets/45608438/e607ddc0-0dcc-49b1-87d9-7ccbcc2a8425)

**Comment by tammy-culture** [comment]
![Image](https://github.com/culturecreates/footlight-app/assets/45608438/5e391fbf-7cd1-48fa-b09b-29706cb2f5b2)

**Comment by tammy-culture** [comment]
This is a French widget and the calendar is appearing in English.

![Image](https://github.com/culturecreates/footlight-app/assets/45608438/c2890fdf-37e1-4ae8-b568-e9bc566da0cb)

**Comment by saumier** [comment]
@tammy-culture I reviewed and all looks good except the months in French are written with a lowercase. So March should be mars. 

>  Specifically the dates like March should be mars in French.

**Comment by tammy-culture** [comment]
@sahalali This is in review but I do not see any changes in production CMS.

**Comment by troughc** [comment]
Caitlin is testing this in the PR so we can push it today. I will show Tammy the process for your future testing. 
- Hauteur appears: FIXED
- Dici.ca appears: FIXED
- Dici widget is in French: FIXED
- downstyle (all lowercase) for months in French in calendar date picker: PENDING
- default language for widget is french for bilingual calendars: PENDING
-
