### ISSUE TITLE
Change Read-Only Pages Functionality

### ISSUE THREAD

**Issue by SyamBabu-M** [culturecreates/footlight-app#1187]
[FIGMA](https://www.figma.com/design/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?node-id=9976-94090&t=5hMwYHR3XrayddVh-0)

```[tasklist]
### Tasks
- [x] Convert the read only page to tab styled. Each content language should have a seperate tab.
- [ ] https://github.com/culturecreates/footlight-app/issues/1223
- [x] Integrate new content language type to existing components. Change static content language handling and adapt dynamic handling
```

**Comment by SyamBabu-M** [comment]
@troughc @saumier In the new design, when a particular field is missing a value in a specific language, how should we handle it on the read-only page for that language?

For instance, if an event does not have a Korean name, what should be displayed in the Korean read-only view? Should we show a placeholder, leave it blank, or indicate that the value is unavailable in that language?

cc @AbhishekPAnil

**Comment by SyamBabu-M** [comment]
@troughc Our widget currently supports only two languages: French and English. If a calendar is configured with unsupported languages, such as Chinese and Japanese, which languages should be displayed in the language selection tab of the widget settings page?

Currently, if the calendar has only one language (e.g., French, as in the Singe Laval calendar), only French is shown in the dropdown for selecting the widget language.

**Comment by troughc** [comment]
> [@troughc](https://github.com/troughc) [@saumier](https://github.com/saumier) In the new design, when a particular field is missing a value in a specific language, how should we handle it on the read-only page for that language?
> 
> For instance, if an event does not have a Korean name, what should be displayed in the Korean read-only view? Should we show a fallback value, leave it blank, or indicate that the value is unavailable in that language?

@SyamBabu-M Here is my guidance:  

When the person hasn't explicitly chosen/entered text in a field like title, cisplay the field label and then leave the space below blank.  Examples: 
- for an event title on all the read-only pages viewed in a **French** UI, display "Titre de l'événement" and leave a blank space below (where the title would go in bold).
- for an event title on all the read-only pages viewed in a **English** UI, display "Event title" and leave a blank space below (where the title would go in bold).
- Once the person goes into the edit page and either accepts a fallback language (thereby creating a new language literal for the specific language page) or enters some text into that language field, you would display the user chosen text on the read only page next time they view it.

ALSO
Please ALWAYS display fields that are mandatory. For example, if Event type is mandatory for the particular calendar, display Event type with a blank below it (if the user hasn't entered and saved an event type yet).

> 
> 2 - Our widget currently supports only two languages: French and English. If a calendar is configured with unsupported languages, such as Chinese and Japanese, which languages should be displayed in the language selection tab of the widget settings page?

All languages that are configured in a calendar should be available in the dropdown for the widget (so a user can share a widget in any of the languages they have configured). 
@SyamBabu-M how much work would it be to add new languages to the widget? Can you estimate this for me before proceeding?

> Currently, if the calendar has only one language (e.g., French, as in the Singe Laval calendar), only French is shown in the dropdown for selecting the widget language.
Yes, this makes sense

cc @AbhishekPAnil @saumier

**Comment by SyamBabu-M** [comment]
> All languages that are configured in a calendar should be available in the dropdown for the widget (so a user can share a widget in any of the languages they have configured).
> [@SyamBabu-M](https://github.com/SyamBabu-M) how much work would it be to add new languages to the widget? **Can you estimate this for me before proceeding?**

Based on my estimation, it would take approximately 6 hours to add new languages to the widget.

Currently, the widget settings offer a single option for selecting a language, which is then used for both the interface and content language. This means the chosen language is applied for both formatting dates and displaying the calendar and during data transformation.

I can show you a demo after the standup today.

**Comment by SyamBabu-M** [comment]
> [@SyamBabu-M](https://github.com/SyamBabu-M) Here is my guidance:
> 
> When the person hasn't explicitly chosen/entered text in a field like title, cisplay the field label and then leave the space below blank. Examples:
> 
> * for an event title on all the read-only pages viewed in a **French** UI, display "Titre de l'événement" and leave a blank space below (where the title would go in bold).
> * for an event title on all the read-only pages viewed in a **English** UI, display "Event title" and leave a blank space below (where the title would go in bold).
> * Once the person goes into the edit page and either accepts a fallback language (thereby creating a new language literal for the specific language page) or enters some text into that language field, you would display the user chosen text on the read only page next time they view it.
> 
> ALSO Please ALWAYS display fields that are mandatory. For example, if Event type is mandatory for the particular calendar, display Event type with a blank below it (if the user hasn't entered and saved an event type yet).

Before implementing this I would like to know if the behaviour will be same for concepts in taxonomy page. For instance, if a concept name is not available in a particular language, what should be displayed? This is crucial for development because I’m using the same function in both the read-only pages and taxonomy form, and changes in one could impact the other.

**Comment by troughc** [comment]
@SyamBabu-M for now, we won't add any more languages to the widget. The widget will continue to be available in english and french only.

**Comment by troughc** [comment]
@SyamBabu-M 2 things; 
First, regarding my comment 
_Please ALWAYS display fields that are mandatory. For example, if Event type is mandatory for the particular calendar, display Event type with a blank below it (if the user hasn't entered and saved an event type yet)._
This still need to be implemented.
Second, regarding display of fallback languages on read-only pages. As per today's discussion, on read-only pages, please display a fallback language (incuding @none )  if it is available.

**Comment by troughc** [comment]
@SyamBabu-M I am assuming this will be taken care of with 1001.

**Comment by troughc** [comment]
@SyamBabu-M question: is this fixed in staging? I ask because we are testing the events that are being imported into the ArtscultureNB calendar from the four aggregators and noticed the following issues with @none display in the listing page, the read-only page and the edit page. I am adding my questions / issues here so that you can check. 
For both the acapitol-nb and the ascenefrancophone sets of events:
First, in the Edit page, the language **literal tag for @none is displayed over the html tags** in the Description field (because it is longer than @fr and @en). 
![Image](https://github.com/user-attachments/assets/aaf6c0d4-b0ef-473c-91ca-1eb60e68e4c3)

**Comment by troughc** [comment]
@sahalali I am changing my mind. i will open an new issue for the problem above and close this one. I think everything else is implemented. Please let me know if you disagree (at tomrrow's standup).
