### ISSUE TITLE
Style and functionality changes of input component to include support for additional content languages

### ISSUE THREAD

**Issue by SyamBabu-M** [culturecreates/footlight-app#1189]
```[tasklist]
### Tasks
- [x] Handiling language literal functionality in newly update input components
- [x] Design Changes of tabs.
- [x] New Language tabs in input component.
- [x] Add more content languages
- [x] Integrate new content language type to existing components. Change static content language handling and adapt dynamic handling
- [x] Replace old input form item component with new dynamic component
- [ ] Peer review of enitre form pages
```

**Comment by SyamBabu-M** [comment]
@SuhailAliyar @dev-aravind The list of languages need to be added in Calender details get API. Currrently we are handling this with contentLanguage field that can only take values of FRENCH, ENGLISH or BILINGUAL. It need to be converted to an array of languages.

**Comment by dev-aravind** [comment]
@SyamBabu-M If the languages are passed as empty strings, i.e. "" then the language fallbacks are not working in the people and organization forms. Please take a look into this.

**Comment by troughc** [comment]
Notes from meeting with @SyamBabu-M and @troughc 
Syam: will take the 'spreadsheet' approach (not tabs) for the concept list
Syam: remove semi-colons from the language labels at the top
Syam: when there are only 2 languages, do not have scroll bar, otherwise do have one.
Caitlin/Design: when 3 or more tabs, do we need some kind of indicator for user to scroll to see other languages? both ways?
Caitlin/Design: what design changes if any are needed for the language labels in the spreadsheet concept approach? Also in other multi-language fields
Caitlin/Design: what can we do with the warning symbol - it causes the tabs to overflow the space (get 3 dots), should we use a colour instead, have a popup. What is the best approach?


QUESTIONS
What if a concept does not have korean language but the listing site includes a korean page, do we use the fallback language: YES
What fallback language should be used? Should this be done in frontend or backend?

do we show the language literal tag when a concept is replaced by a fallback language? Where would this appear - in tree or in edit popup dialog box

**Comment by troughc** [comment]
Note for @SyamBabu-M I have added a new 'enhancement' issue for implementing the 'spreadsheet' approach in taxonomies. Please find it [here](https://github.com/culturecreates/footlight-app/issues/1302)
