### ISSUE TITLE
Only update language if a field is edited in Edit view and is not empty when saved

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1394]
Reference user story: https://github.com/culturecreates/footlight-app/issues/1371
### Current behaviour - to be replaced with new behaviour
Events: **Publishing** an entity creates literals in a language field based on the displayed fallback language when the field was not touched 
Events: **Saving** an event entity does NOT create a literal in a language field based on the fallback language when the field is not touched
Place/Person/Org: **Saving** an entity creates a literal in a language field based on a displayed fallback language when the field was not touched

### New behaviour
1. Make events, places, persons and orgs all behave the same way when it comes to creating a literal in a language field.
- Remove the difference between saving and publishing in Events
- Make Save behave the same across all classes / entity types using Event saving behaviour as the model
2. **Saving (publishing) an entity** will only create a literal in a field that a user explicitly touched (edited) and has something in it (a text string). It will not create a literal in a field that is untouched:
- All entities: **Saving** an event entity will NOT create a literal in a language field based on the fallback language when the field is NOT touched
- Events: **Publishing** an event entity will NOT create a literal in a language field based on the fallback language when the field is NOT touched
3. Warnings will continue to appear to inform the user that there is content doesn't match the language on the website until all fields have been touched / updated (I believe this continues to work as is, no change)
4. In Edit view: what happens if the user touches / clicks in a field and deletes the fallback language text that is displayed, but does not replace it with anything (i.e. leaves the field empty)? A literal will not be created, i.e. we will NOT create a literal that is blank upon saving/publishing. Instead, the next time someone views that entity in Edit mode, the fallback language will be displayed.
5. TO BE DECIDED for Read-only view: I am still debating which approach to take if a fallback language is being displayed because there is no language literal. In the read-only view, should we:
- Show a field as empty, i.e. stop displaying the fallback language?
- Display the fallback language in the field and display the language literal tag (this would be a change)?
- leave it as is
6. In List views: leave it as is, no change.

```[tasklist]
### Tasks
- [x] Change logic of dismiss button in warning banner of each page.
- [x] Redux slice change to accomodate new requirement.
- [x] Change logic in save function accross all entities except event page.
- [x] Change publishing logic in events page.
- [x] Change taxonomy concept logic to determine if field is dirty.
```

**Comment by saumier** [comment]
@troughc Looks good.

**Comment by SyamBabu-M** [comment]
@troughc @saumier What happens when "dismiss" is pressed in the banner, which indicates there are language fallbacks present?
Currently, pressing dismiss will enable all fallback values to be their active value. And upon saving these values will be saved.

**Comment by troughc** [comment]
> @troughc @saumier What happens when "dismiss" is pressed in the banner, which indicates there are language fallbacks present?
> Currently, pressing dismiss will enable all fallback values to be their active value. And upon saving these values will be saved

@SyamBabu-M 'Dismiss' should not enable the fallback languages to be the active value which is then saved (the fallback languages as the actual values). Dismiss is used by a user to close the banner only.

The big idea/goal is that the user intentionally sets (chooses) the fallback language as the active value. Let me know if you need any further clarification.

**Comment by SyamBabu-M** [comment]
@dev-aravind Please do a round of peer review.

**Comment by dev-aravind** [comment]
@SyamBabu-M This looks good to me but the regression tests for places is failing. Please look into this. You can find the screenshots [here](https://github.com/culturecreates/footlight-app/actions/runs/12178915914/artifacts/2278976266).

**Comment by SyamBabu-M** [comment]
@troughc Please test this in staging

**Comment by troughc** [comment]
Tested starting with Events.
Test event: https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/67574344200bdc00a2ce2116

1. **Saving (publishing)** an entity will only create a literal in a field that a user explicitly touched (edited) and has something in it (a text string). It will not create a literal in a field that is untouched: PLEASE CHECK

It looks like it is partially working. 
However, I have had some inconsistent results that I would like you to check into.
First, in the Description field.
For this [test event](https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/67574344200bdc00a2ce2116
), I entered a English and French description. Then I went back in, after publishing, and the Description field didn't have literal tags displayed for japanese and korean (even though I don't think I touched them).

I tried it again in [this event](https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/67574614200bdc00a2ce2426): 
This time, the description field worked as expected after saving and after publishing (PASSED). So maybe it was user error? But i would appreciate it if. you could test again, to see if you see anything not working.

2. **NEXT: the fallback language** in the read-only page is. not the same as the fallback language in the Edit page for both test events.

In read only, it looks like it is FRENCH
In Edit view: it is ENGLISH.

I think this is because I changed the order of languages in settings before creating my events. I change the order from having FRENCH first to haviing ENGLISH first (which changed the fallback language from French to English).
So, the expected behaviour is that the fallback langauge is the same in REad only as in Edit view; and that the fallback language in my specific example is ENGLISH (the first language in the list in settings).

### wrong fallback language in read only
![Image](https://github.com/user-attachments/assets/823b99f2-4ae1-41c8-b83f-cf9aa3c913cc)

### right fallback language in edit view
![Image](https://github.com/user-attachments/assets/a836d2cf-35b3-4334-99ab-a6b25f4aa89d)

3. Tested in organizations with [2freres](https://staging.cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/organizations/6629f52d0796c3006456e815)
To set it up, I removed the text from the Name and the Description fields. 
The name field works as expected (the fallback language was displayed into the empty fields); and the entity saved correctly (no new language literal was created).
The Description field behaved differntly - the fields were left empty (no fallback language was displayed into the empty fields) and it saved with them blank (in read-only view and in edit view).

![Image](https://github.com/user-attachments/assets/bc9004b2-f60d-4e4b-9125-d102d16e8203)

**Comment by SyamBabu-M** [comment]
> 2. the fallback language in the read-only page is not the same as the fallback language in the Edit page for both test events.

I have not changed anything on the read-only pages as this was not within the scope of this ticket. Should we address this issue before this goes live? Or we can work on that as a separate issue.

> 1. Saving (publishing) an entity will only create a literal in a field that a user explicitly touched (edited) and has something in it (a text string). It will not create a literal in a field that is untouched: PLEASE CHECK

This is an issue with tesx editor. I'll fix this asap.

**Comment by SyamBabu-M** [comment]
I have fixed the bug with editors unusual behavior. please test this in the linked PR.

**Comment by troughc** [comment]
Tested the text editor behaviour: PASSED.
@SyamBabu-M I will create an issue for the read only page. We may also use this opportunity to add the language literal tag to read-only pages as well, when a fallback language is being used (displayed) in lieu of a missing text string.

**Comment by troughc** [comment]
@SyamBabu-M I just found a minor bug - the ticketing fields in the Edit view are not displaying fallback languages and the literal tag when they are empty. See [this event](https://pr-1505.dla06mbe0wyl7.amplifyapp.com/dashboard/6308ef4a7f771f00431d939a/events/add-event/663517a50796c300645c23f3)
### Example: empty field in Japanese
<img width="482" alt="Screenshot 2024-12-11 at 1 47 00 PM" src="https://github.com/user-attachments/assets/3b976587-a742-4632-a9a8-f26cab8b77fa" />

This is a minor bug so you can decide to deploy this update as is or you can fix this first. Either way, I will add this minor bug to the other ticket I am creating.
