### ISSUE TITLE
Sprint Overview: adding event details to the Widget

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#1499]
Document with user story and guidelines for this first sprint:
Event Calendar Widget MVP 
https://docs.google.com/document/d/1zvoqpjExjs8HmvBSyx1p1hl6GIUdhMuxt3ZHjuq6bp0/edit?tab=t.0

Please hold a design meeting on Monday to figure out how to achieve the goal, and create separate Github issues that will fit within this 2 week sprint.

At the Monday standup we can review the plan together and answer any questions.

```[tasklist]
### Tasks
- [x] Research viability of using package of popup modal.
- [x] Modal UI creation and data integration.
- [x] Redirection type parameter integration (CMS side).
- [x] Redirection parameter integration in widget. Current code refactor.
- [x] Filter option UI creation and API integration
```

```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/footlight-app/issues/1503
- [ ] https://github.com/culturecreates/footlight-app/issues/1504
- [ ] https://github.com/culturecreates/footlight-calendar-widget/issues/53
- [ ] https://github.com/culturecreates/footlight-app/issues/1514
```

**Comment by troughc** [comment]
FYI for everyone: NAC is okay with us publishing the events. i have gone ahead and published several of them in production. 
Note that dates, times and venues are placeholders but they work.

**Comment by AbhishekPAnil** [comment]
@troughc If everything is functioning correctly, can we consider closing this issue ?

**Comment by troughc** [comment]
As discussed we will wait until widget is pushed to production. :)

**Comment by saumier** [comment]
@SyamBabu-M Please take a look at this widget integration. I am hoping that I can show it to NAC today. 
https://culturecreates.github.io/footlight-widget-demo/art-cms-div-widget.html
