### ISSUE TITLE
Adding event details to widget - Frontend work on CMS side.

### ISSUE THREAD

**Issue by SyamBabu-M** [culturecreates/footlight-app#1503]
Refer doc [Event Calendar Widget MVP](https://docs.google.com/document/d/1zvoqpjExjs8HmvBSyx1p1hl6GIUdhMuxt3ZHjuq6bp0/edit?tab=t.0#heading=h.9breajq5kssg)
```[tasklist]
### Tasks
- [x] Add parameter “Redirection type” as dropdown. - estimate: 2h.
- [x] Logic to enable only popup type widget if template URLs are not provided - estimate: 3h
- [x] Integration of Performing group/artist/event animator as ne param into Iframe. Seperate it from Event Organizer. - estimate: 1h
- [x] Testing - both CMS side and Widget side - estimate: 2h
```

**Comment by troughc** [comment]
@SyamBabu-M this is looking good. A couple comments:
- in the PR, no images are displayed so I added a few and they are working well: PASS
- I tested that the language updates in the widget when I switch: PASS
- Performer is showing up in the details view: PASS
- Performer image - not there - should it be @saumier ?
- @SyamBabu-M when I open the event details in the CMS preview, the description is including lorem ipsum text that is not in the description. Please check this and remove any extra placeholder text that should not be there. Here is a screenshot:
<img width="1004" alt="Screenshot 2024-12-16 at 1 24 33 PM" src="https://github.com/user-attachments/assets/5e3ae019-f3c5-4e36-8a4e-2ac99be4c26f" />

**Comment by SyamBabu-M** [comment]
@dev-aravind Please add performer images in the [Open API response](https://api.footlight.io/api/#/Calendar%20APIs/CalendarController_getEventsByCalendarId).

**Comment by dev-aravind** [comment]
@SyamBabu-M The performer images are also now returned in the open-api side.

**Comment by SyamBabu-M** [comment]
> * Performer image - not there - please add the performer image thumbnail as per the design in [Sprint Overview: adding event details to the Widget #1499](https://github.com/culturecreates/footlight-app/issues/1499)
> * [@SyamBabu-M](https://github.com/SyamBabu-M) when I open the event details in the CMS preview, the description is including lorem ipsum text that is not in the description. Please check this and remove any extra placeholder text that should not be there. Here is a screenshot:

I have made these changes. Please test again and let me know what you think.

**Comment by troughc** [comment]
TESTED: PASSED
Performer image - not there - please add the performer image thumbnail as per the design in https://github.com/culturecreates/footlight-app/issues/1499 : PASSED
@SyamBabu-M when I open the event details in the CMS preview, the description is including lorem ipsum text that is not in the description. Please check this and remove any extra placeholder text that should not be there: PASSED
