### ISSUE TITLE
Enhancement: Add Taxonomy filter for classes

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#689]
Feature enhancement to add a filter to the Taxonomy listing page called "Class". The user would then use this filter to view all the taxonomies within a selected class(es).
The design should be the same as used for Events, and it could be muti-select filter like the filters in Events. 
The Clear button should be included (same functionality as in Events).

Examples of expected behaviour:
The user selects Events from the dropdown. All the taxonomies related to the Events class are displayed in the list. The Clear button appears.

The user selects People and Organizations. All taxonomies related to People and Organizations are displayed in the list. The clear button is displayed.

User clicks Clear to clear the filter selection and set the list back to its default.

```[tasklist]
### Tasks
- [x] Add the "Class" filter button including translations.
- [x] Add the multi-select dropdown for  class filter
- [x] Api integration to add class filter
- [x] Clear the class filter upon clicking the Clear button
```

**Comment by troughc** [comment]
@AbhishekPAnil can you please provide an estimate for this.

**Comment by AbhishekPAnil** [comment]
> @AbhishekPAnil can you please provide an estimate for this.

Updated the issue with the estimate and tasklist.

**Comment by SyamBabu-M** [comment]
@dev-aravind Currently the filter in get API accepts Taxonomy class as a string(only one class can be selected at a time). Please change it so that I can filter by multiple classes.

**Comment by dev-aravind** [comment]
@SyamBabu-M The changes are up in staging

**Comment by troughc** [comment]
Testing staging on Chrome: 
Works well, just have a mislabeled filter button
- "User types" should be labeled "Class types"

**Comment by troughc** [comment]
@SyamBabu-M I retested this and the label is correct. I needed to do a hard reload. Thanks!
Tested on Chrome: PASSED
