### ISSUE TITLE
Mobile / Tablet views of details forms - layout

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-app#895]
Discuss at next sprint review with @sahalali whether this should be one issue or several.

The details forms for different entities need to be adjusted to match the figmas for mobile (and tablet) versions.
Note: Taxonomy and settings are not designed yet.

Here are a couple of examples of things that will change:
Event form
- A + symbol in each section for "add more details" is needed. This + symbol opens an Add more details popup
- Some of the entry fields need to be less wide to fit on mobile screens (date range field, location field, accessiblity...) 

Here are links to the mobile (and tablet) designs for the details forms:
**Events:** https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=7317-19842&mode=dev
**Places:** https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=7469-37493&mode=dev
**Organizations:** https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=7469-37494&mode=dev
**People:** https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=7469-37495&mode=dev
**Taxonomies:** https://www.figma.com/file/DBnSSMT9Etfm6guDKKSp8O/Culture-Creates---Footlight-Calendar?type=design&node-id=8151-37132&mode=dev

cc @AbhishekPAnil @SyamBabu-M 

```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/footlight-app/issues/964
- [ ] https://github.com/culturecreates/footlight-app/issues/968
- [ ] https://github.com/culturecreates/footlight-app/issues/967
- [ ] https://github.com/culturecreates/footlight-app/issues/965
- [ ] https://github.com/culturecreates/footlight-app/issues/966
- [ ] https://github.com/culturecreates/footlight-app/issues/940
```

**Comment by SyamBabu-M** [comment]
@troughc Added the [estimate](https://docs.google.com/spreadsheets/d/1bcJQuIafrvokZ01MJT7jlrs9gwOHiD1im2QqhLtD5yw/edit#gid=0)

**Comment by sahalali** [comment]
@SyamBabu-M Can you please split this issue to workable atomic issues?

**Comment by sahalali** [comment]
@SyamBabu-M Can you please add checkbox with the atomic tasks.

**Comment by saumier** [comment]
@SyamBabu-M  Looks good. I played around with the Event type taxonomy on my iPhone and I was able to change the order in the tree.

**Comment by troughc** [comment]
@SuhailAliyar - question from Monday (next week): did this issue get deployed to production already?

**Comment by SyamBabu-M** [comment]
Yes. This was deployed to production.
